name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Remove existing .env and copy .env.example
      run: |
        rm -f .env
        cp .env.example .env
    - name: Install Dependencies
      run: composer install  --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --prefer-source
    - name: Install Node Dependencies
      run: npm install
    - name: Build Assets
      run: npm run build
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Generate key
      env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      run: php artisan key:generate
    - name: Run Migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force    
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        COMPOSER_PROCESS_TIMEOUT: 600
      run: php artisan test
